(* Generated by gen/gen_tables.exe from vendor/pcre2/src/pcre2_ucptables.c (PCRE2 10.44). DO NOT EDIT. *)

(* pcre2_ucptables.c:1037-1527 - PRIV(utt), with the name offsets into
   PRIV(utt_names) (pcre2_ucptables.c:546-1035) resolved to the name
   strings. Entries are (name, ptype, pvalue): ptype is a PT_* constant
   (pcre2_internal.h:1293-1306), pvalue a ucp_* enum value (pcre2_ucp.h,
   see ucp.ml). Searched by binary chop, so names are in strictly
   ascending order; they are lower cased with underscores removed, per
   Unicode "loose matching". *)
let utt : (string * int * int) array =
  [|
    ("adlam", 5, 58);
    (* PT_SCX, ucp_Adlam *)
    ("adlm", 5, 58);
    (* PT_SCX, ucp_Adlam *)
    ("aghb", 4, 125);
    (* PT_SC, ucp_Caucasian_Albanian *)
    ("ahex", 13, 1);
    (* PT_BOOL, ucp_ASCII_Hex_Digit *)
    ("ahom", 4, 137);
    (* PT_SC, ucp_Ahom *)
    ("alpha", 13, 2);
    (* PT_BOOL, ucp_Alphabetic *)
    ("alphabetic", 13, 2);
    (* PT_BOOL, ucp_Alphabetic *)
    ("anatolianhieroglyphs", 4, 138);
    (* PT_SC, ucp_Anatolian_Hieroglyphs *)
    ("any", 0, 0);
    (* PT_ANY, 0 *)
    ("arab", 5, 3);
    (* PT_SCX, ucp_Arabic *)
    ("arabic", 5, 3);
    (* PT_SCX, ucp_Arabic *)
    ("armenian", 4, 70);
    (* PT_SC, ucp_Armenian *)
    ("armi", 4, 114);
    (* PT_SC, ucp_Imperial_Aramaic *)
    ("armn", 4, 70);
    (* PT_SC, ucp_Armenian *)
    ("ascii", 13, 0);
    (* PT_BOOL, ucp_ASCII *)
    ("asciihexdigit", 13, 1);
    (* PT_BOOL, ucp_ASCII_Hex_Digit *)
    ("avestan", 4, 108);
    (* PT_SC, ucp_Avestan *)
    ("avst", 4, 108);
    (* PT_SC, ucp_Avestan *)
    ("bali", 4, 93);
    (* PT_SC, ucp_Balinese *)
    ("balinese", 4, 93);
    (* PT_SC, ucp_Balinese *)
    ("bamu", 4, 112);
    (* PT_SC, ucp_Bamum *)
    ("bamum", 4, 112);
    (* PT_SC, ucp_Bamum *)
    ("bass", 4, 126);
    (* PT_SC, ucp_Bassa_Vah *)
    ("bassavah", 4, 126);
    (* PT_SC, ucp_Bassa_Vah *)
    ("batak", 4, 119);
    (* PT_SC, ucp_Batak *)
    ("batk", 4, 119);
    (* PT_SC, ucp_Batak *)
    ("beng", 5, 7);
    (* PT_SCX, ucp_Bengali *)
    ("bengali", 5, 7);
    (* PT_SCX, ucp_Bengali *)
    ("bhaiksuki", 4, 142);
    (* PT_SC, ucp_Bhaiksuki *)
    ("bhks", 4, 142);
    (* PT_SC, ucp_Bhaiksuki *)
    ("bidial", 12, 0);
    (* PT_BIDICL, ucp_bidiAL *)
    ("bidian", 12, 1);
    (* PT_BIDICL, ucp_bidiAN *)
    ("bidib", 12, 2);
    (* PT_BIDICL, ucp_bidiB *)
    ("bidibn", 12, 3);
    (* PT_BIDICL, ucp_bidiBN *)
    ("bidic", 13, 3);
    (* PT_BOOL, ucp_Bidi_Control *)
    ("bidicontrol", 13, 3);
    (* PT_BOOL, ucp_Bidi_Control *)
    ("bidics", 12, 4);
    (* PT_BIDICL, ucp_bidiCS *)
    ("bidien", 12, 5);
    (* PT_BIDICL, ucp_bidiEN *)
    ("bidies", 12, 6);
    (* PT_BIDICL, ucp_bidiES *)
    ("bidiet", 12, 7);
    (* PT_BIDICL, ucp_bidiET *)
    ("bidifsi", 12, 8);
    (* PT_BIDICL, ucp_bidiFSI *)
    ("bidil", 12, 9);
    (* PT_BIDICL, ucp_bidiL *)
    ("bidilre", 12, 10);
    (* PT_BIDICL, ucp_bidiLRE *)
    ("bidilri", 12, 11);
    (* PT_BIDICL, ucp_bidiLRI *)
    ("bidilro", 12, 12);
    (* PT_BIDICL, ucp_bidiLRO *)
    ("bidim", 13, 4);
    (* PT_BOOL, ucp_Bidi_Mirrored *)
    ("bidimirrored", 13, 4);
    (* PT_BOOL, ucp_Bidi_Mirrored *)
    ("bidinsm", 12, 13);
    (* PT_BIDICL, ucp_bidiNSM *)
    ("bidion", 12, 14);
    (* PT_BIDICL, ucp_bidiON *)
    ("bidipdf", 12, 15);
    (* PT_BIDICL, ucp_bidiPDF *)
    ("bidipdi", 12, 16);
    (* PT_BIDICL, ucp_bidiPDI *)
    ("bidir", 12, 17);
    (* PT_BIDICL, ucp_bidiR *)
    ("bidirle", 12, 18);
    (* PT_BIDICL, ucp_bidiRLE *)
    ("bidirli", 12, 19);
    (* PT_BIDICL, ucp_bidiRLI *)
    ("bidirlo", 12, 20);
    (* PT_BIDICL, ucp_bidiRLO *)
    ("bidis", 12, 21);
    (* PT_BIDICL, ucp_bidiS *)
    ("bidiws", 12, 22);
    (* PT_BIDICL, ucp_bidiWS *)
    ("bopo", 5, 22);
    (* PT_SCX, ucp_Bopomofo *)
    ("bopomofo", 5, 22);
    (* PT_SCX, ucp_Bopomofo *)
    ("brah", 4, 120);
    (* PT_SC, ucp_Brahmi *)
    ("brahmi", 4, 120);
    (* PT_SC, ucp_Brahmi *)
    ("brai", 4, 88);
    (* PT_SC, ucp_Braille *)
    ("braille", 4, 88);
    (* PT_SC, ucp_Braille *)
    ("bugi", 5, 33);
    (* PT_SCX, ucp_Buginese *)
    ("buginese", 5, 33);
    (* PT_SCX, ucp_Buginese *)
    ("buhd", 5, 27);
    (* PT_SCX, ucp_Buhid *)
    ("buhid", 5, 27);
    (* PT_SCX, ucp_Buhid *)
    ("c", 2, 0);
    (* PT_GC, ucp_C *)
    ("cakm", 5, 43);
    (* PT_SCX, ucp_Chakma *)
    ("canadianaboriginal", 4, 77);
    (* PT_SC, ucp_Canadian_Aboriginal *)
    ("cans", 4, 77);
    (* PT_SC, ucp_Canadian_Aboriginal *)
    ("cari", 4, 103);
    (* PT_SC, ucp_Carian *)
    ("carian", 4, 103);
    (* PT_SC, ucp_Carian *)
    ("cased", 13, 6);
    (* PT_BOOL, ucp_Cased *)
    ("caseignorable", 13, 5);
    (* PT_BOOL, ucp_Case_Ignorable *)
    ("caucasianalbanian", 4, 125);
    (* PT_SC, ucp_Caucasian_Albanian *)
    ("cc", 3, 0);
    (* PT_PC, ucp_Cc *)
    ("cf", 3, 1);
    (* PT_PC, ucp_Cf *)
    ("chakma", 5, 43);
    (* PT_SCX, ucp_Chakma *)
    ("cham", 4, 105);
    (* PT_SC, ucp_Cham *)
    ("changeswhencasefolded", 13, 7);
    (* PT_BOOL, ucp_Changes_When_Casefolded *)
    ("changeswhencasemapped", 13, 8);
    (* PT_BOOL, ucp_Changes_When_Casemapped *)
    ("changeswhenlowercased", 13, 9);
    (* PT_BOOL, ucp_Changes_When_Lowercased *)
    ("changeswhentitlecased", 13, 10);
    (* PT_BOOL, ucp_Changes_When_Titlecased *)
    ("changeswhenuppercased", 13, 11);
    (* PT_BOOL, ucp_Changes_When_Uppercased *)
    ("cher", 4, 76);
    (* PT_SC, ucp_Cherokee *)
    ("cherokee", 4, 76);
    (* PT_SC, ucp_Cherokee *)
    ("chorasmian", 4, 156);
    (* PT_SC, ucp_Chorasmian *)
    ("chrs", 4, 156);
    (* PT_SC, ucp_Chorasmian *)
    ("ci", 13, 5);
    (* PT_BOOL, ucp_Case_Ignorable *)
    ("cn", 3, 2);
    (* PT_PC, ucp_Cn *)
    ("co", 3, 3);
    (* PT_PC, ucp_Co *)
    ("common", 4, 69);
    (* PT_SC, ucp_Common *)
    ("copt", 5, 34);
    (* PT_SCX, ucp_Coptic *)
    ("coptic", 5, 34);
    (* PT_SCX, ucp_Coptic *)
    ("cpmn", 5, 66);
    (* PT_SCX, ucp_Cypro_Minoan *)
    ("cprt", 5, 32);
    (* PT_SCX, ucp_Cypriot *)
    ("cs", 3, 4);
    (* PT_PC, ucp_Cs *)
    ("cuneiform", 4, 94);
    (* PT_SC, ucp_Cuneiform *)
    ("cwcf", 13, 7);
    (* PT_BOOL, ucp_Changes_When_Casefolded *)
    ("cwcm", 13, 8);
    (* PT_BOOL, ucp_Changes_When_Casemapped *)
    ("cwl", 13, 9);
    (* PT_BOOL, ucp_Changes_When_Lowercased *)
    ("cwt", 13, 10);
    (* PT_BOOL, ucp_Changes_When_Titlecased *)
    ("cwu", 13, 11);
    (* PT_BOOL, ucp_Changes_When_Uppercased *)
    ("cypriot", 5, 32);
    (* PT_SCX, ucp_Cypriot *)
    ("cyprominoan", 5, 66);
    (* PT_SCX, ucp_Cypro_Minoan *)
    ("cyrillic", 5, 2);
    (* PT_SCX, ucp_Cyrillic *)
    ("cyrl", 5, 2);
    (* PT_SCX, ucp_Cyrillic *)
    ("dash", 13, 12);
    (* PT_BOOL, ucp_Dash *)
    ("defaultignorablecodepoint", 13, 13);
    (* PT_BOOL, ucp_Default_Ignorable_Code_Point *)
    ("dep", 13, 14);
    (* PT_BOOL, ucp_Deprecated *)
    ("deprecated", 13, 14);
    (* PT_BOOL, ucp_Deprecated *)
    ("deseret", 4, 83);
    (* PT_SC, ucp_Deseret *)
    ("deva", 5, 6);
    (* PT_SCX, ucp_Devanagari *)
    ("devanagari", 5, 6);
    (* PT_SCX, ucp_Devanagari *)
    ("di", 13, 13);
    (* PT_BOOL, ucp_Default_Ignorable_Code_Point *)
    ("dia", 13, 15);
    (* PT_BOOL, ucp_Diacritic *)
    ("diacritic", 13, 15);
    (* PT_BOOL, ucp_Diacritic *)
    ("diak", 4, 157);
    (* PT_SC, ucp_Dives_Akuru *)
    ("divesakuru", 4, 157);
    (* PT_SC, ucp_Dives_Akuru *)
    ("dogr", 5, 60);
    (* PT_SCX, ucp_Dogra *)
    ("dogra", 5, 60);
    (* PT_SCX, ucp_Dogra *)
    ("dsrt", 4, 83);
    (* PT_SC, ucp_Deseret *)
    ("dupl", 5, 46);
    (* PT_SCX, ucp_Duployan *)
    ("duployan", 5, 46);
    (* PT_SCX, ucp_Duployan *)
    ("ebase", 13, 19);
    (* PT_BOOL, ucp_Emoji_Modifier_Base *)
    ("ecomp", 13, 17);
    (* PT_BOOL, ucp_Emoji_Component *)
    ("egyp", 4, 109);
    (* PT_SC, ucp_Egyptian_Hieroglyphs *)
    ("egyptianhieroglyphs", 4, 109);
    (* PT_SC, ucp_Egyptian_Hieroglyphs *)
    ("elba", 4, 127);
    (* PT_SC, ucp_Elbasan *)
    ("elbasan", 4, 127);
    (* PT_SC, ucp_Elbasan *)
    ("elym", 4, 153);
    (* PT_SC, ucp_Elymaic *)
    ("elymaic", 4, 153);
    (* PT_SC, ucp_Elymaic *)
    ("emod", 13, 18);
    (* PT_BOOL, ucp_Emoji_Modifier *)
    ("emoji", 13, 16);
    (* PT_BOOL, ucp_Emoji *)
    ("emojicomponent", 13, 17);
    (* PT_BOOL, ucp_Emoji_Component *)
    ("emojimodifier", 13, 18);
    (* PT_BOOL, ucp_Emoji_Modifier *)
    ("emojimodifierbase", 13, 19);
    (* PT_BOOL, ucp_Emoji_Modifier_Base *)
    ("emojipresentation", 13, 20);
    (* PT_BOOL, ucp_Emoji_Presentation *)
    ("epres", 13, 20);
    (* PT_BOOL, ucp_Emoji_Presentation *)
    ("ethi", 4, 75);
    (* PT_SC, ucp_Ethiopic *)
    ("ethiopic", 4, 75);
    (* PT_SC, ucp_Ethiopic *)
    ("ext", 13, 22);
    (* PT_BOOL, ucp_Extender *)
    ("extendedpictographic", 13, 21);
    (* PT_BOOL, ucp_Extended_Pictographic *)
    ("extender", 13, 22);
    (* PT_BOOL, ucp_Extender *)
    ("extpict", 13, 21);
    (* PT_BOOL, ucp_Extended_Pictographic *)
    ("geor", 5, 17);
    (* PT_SCX, ucp_Georgian *)
    ("georgian", 5, 17);
    (* PT_SCX, ucp_Georgian *)
    ("glag", 5, 35);
    (* PT_SCX, ucp_Glagolitic *)
    ("glagolitic", 5, 35);
    (* PT_SCX, ucp_Glagolitic *)
    ("gong", 5, 61);
    (* PT_SCX, ucp_Gunjala_Gondi *)
    ("gonm", 5, 59);
    (* PT_SCX, ucp_Masaram_Gondi *)
    ("goth", 4, 82);
    (* PT_SC, ucp_Gothic *)
    ("gothic", 4, 82);
    (* PT_SC, ucp_Gothic *)
    ("gran", 5, 47);
    (* PT_SCX, ucp_Grantha *)
    ("grantha", 5, 47);
    (* PT_SCX, ucp_Grantha *)
    ("graphemebase", 13, 23);
    (* PT_BOOL, ucp_Grapheme_Base *)
    ("graphemeextend", 13, 24);
    (* PT_BOOL, ucp_Grapheme_Extend *)
    ("graphemelink", 13, 25);
    (* PT_BOOL, ucp_Grapheme_Link *)
    ("grbase", 13, 23);
    (* PT_BOOL, ucp_Grapheme_Base *)
    ("greek", 5, 1);
    (* PT_SCX, ucp_Greek *)
    ("grek", 5, 1);
    (* PT_SCX, ucp_Greek *)
    ("grext", 13, 24);
    (* PT_BOOL, ucp_Grapheme_Extend *)
    ("grlink", 13, 25);
    (* PT_BOOL, ucp_Grapheme_Link *)
    ("gujarati", 5, 9);
    (* PT_SCX, ucp_Gujarati *)
    ("gujr", 5, 9);
    (* PT_SCX, ucp_Gujarati *)
    ("gunjalagondi", 5, 61);
    (* PT_SCX, ucp_Gunjala_Gondi *)
    ("gurmukhi", 5, 8);
    (* PT_SCX, ucp_Gurmukhi *)
    ("guru", 5, 8);
    (* PT_SCX, ucp_Gurmukhi *)
    ("han", 5, 23);
    (* PT_SCX, ucp_Han *)
    ("hang", 5, 18);
    (* PT_SCX, ucp_Hangul *)
    ("hangul", 5, 18);
    (* PT_SCX, ucp_Hangul *)
    ("hani", 5, 23);
    (* PT_SCX, ucp_Han *)
    ("hanifirohingya", 5, 62);
    (* PT_SCX, ucp_Hanifi_Rohingya *)
    ("hano", 5, 26);
    (* PT_SCX, ucp_Hanunoo *)
    ("hanunoo", 5, 26);
    (* PT_SCX, ucp_Hanunoo *)
    ("hatr", 4, 139);
    (* PT_SC, ucp_Hatran *)
    ("hatran", 4, 139);
    (* PT_SC, ucp_Hatran *)
    ("hebr", 4, 71);
    (* PT_SC, ucp_Hebrew *)
    ("hebrew", 4, 71);
    (* PT_SC, ucp_Hebrew *)
    ("hex", 13, 26);
    (* PT_BOOL, ucp_Hex_Digit *)
    ("hexdigit", 13, 26);
    (* PT_BOOL, ucp_Hex_Digit *)
    ("hira", 5, 20);
    (* PT_SCX, ucp_Hiragana *)
    ("hiragana", 5, 20);
    (* PT_SCX, ucp_Hiragana *)
    ("hluw", 4, 138);
    (* PT_SC, ucp_Anatolian_Hieroglyphs *)
    ("hmng", 4, 128);
    (* PT_SC, ucp_Pahawh_Hmong *)
    ("hmnp", 4, 154);
    (* PT_SC, ucp_Nyiakeng_Puachue_Hmong *)
    ("hung", 4, 140);
    (* PT_SC, ucp_Old_Hungarian *)
    ("idc", 13, 29);
    (* PT_BOOL, ucp_ID_Continue *)
    ("idcontinue", 13, 29);
    (* PT_BOOL, ucp_ID_Continue *)
    ("ideo", 13, 31);
    (* PT_BOOL, ucp_Ideographic *)
    ("ideographic", 13, 31);
    (* PT_BOOL, ucp_Ideographic *)
    ("ids", 13, 30);
    (* PT_BOOL, ucp_ID_Start *)
    ("idsb", 13, 27);
    (* PT_BOOL, ucp_IDS_Binary_Operator *)
    ("idsbinaryoperator", 13, 27);
    (* PT_BOOL, ucp_IDS_Binary_Operator *)
    ("idst", 13, 28);
    (* PT_BOOL, ucp_IDS_Trinary_Operator *)
    ("idstart", 13, 30);
    (* PT_BOOL, ucp_ID_Start *)
    ("idstrinaryoperator", 13, 28);
    (* PT_BOOL, ucp_IDS_Trinary_Operator *)
    ("imperialaramaic", 4, 114);
    (* PT_SC, ucp_Imperial_Aramaic *)
    ("inherited", 4, 84);
    (* PT_SC, ucp_Inherited *)
    ("inscriptionalpahlavi", 4, 117);
    (* PT_SC, ucp_Inscriptional_Pahlavi *)
    ("inscriptionalparthian", 4, 116);
    (* PT_SC, ucp_Inscriptional_Parthian *)
    ("ital", 4, 81);
    (* PT_SC, ucp_Old_Italic *)
    ("java", 5, 40);
    (* PT_SCX, ucp_Javanese *)
    ("javanese", 5, 40);
    (* PT_SCX, ucp_Javanese *)
    ("joinc", 13, 32);
    (* PT_BOOL, ucp_Join_Control *)
    ("joincontrol", 13, 32);
    (* PT_BOOL, ucp_Join_Control *)
    ("kaithi", 5, 41);
    (* PT_SCX, ucp_Kaithi *)
    ("kali", 5, 39);
    (* PT_SCX, ucp_Kayah_Li *)
    ("kana", 5, 21);
    (* PT_SCX, ucp_Katakana *)
    ("kannada", 5, 13);
    (* PT_SCX, ucp_Kannada *)
    ("katakana", 5, 21);
    (* PT_SCX, ucp_Katakana *)
    ("kawi", 4, 162);
    (* PT_SC, ucp_Kawi *)
    ("kayahli", 5, 39);
    (* PT_SCX, ucp_Kayah_Li *)
    ("khar", 4, 92);
    (* PT_SC, ucp_Kharoshthi *)
    ("kharoshthi", 4, 92);
    (* PT_SC, ucp_Kharoshthi *)
    ("khitansmallscript", 4, 158);
    (* PT_SC, ucp_Khitan_Small_Script *)
    ("khmer", 4, 80);
    (* PT_SC, ucp_Khmer *)
    ("khmr", 4, 80);
    (* PT_SC, ucp_Khmer *)
    ("khoj", 5, 48);
    (* PT_SCX, ucp_Khojki *)
    ("khojki", 5, 48);
    (* PT_SCX, ucp_Khojki *)
    ("khudawadi", 5, 55);
    (* PT_SCX, ucp_Khudawadi *)
    ("kits", 4, 158);
    (* PT_SC, ucp_Khitan_Small_Script *)
    ("knda", 5, 13);
    (* PT_SCX, ucp_Kannada *)
    ("kthi", 5, 41);
    (* PT_SCX, ucp_Kaithi *)
    ("l", 2, 1);
    (* PT_GC, ucp_L *)
    ("l&", 1, 0);
    (* PT_LAMP, 0 *)
    ("lana", 4, 106);
    (* PT_SC, ucp_Tai_Tham *)
    ("lao", 4, 73);
    (* PT_SC, ucp_Lao *)
    ("laoo", 4, 73);
    (* PT_SC, ucp_Lao *)
    ("latin", 5, 0);
    (* PT_SCX, ucp_Latin *)
    ("latn", 5, 0);
    (* PT_SCX, ucp_Latin *)
    ("lc", 1, 0);
    (* PT_LAMP, 0 *)
    ("lepc", 4, 97);
    (* PT_SC, ucp_Lepcha *)
    ("lepcha", 4, 97);
    (* PT_SC, ucp_Lepcha *)
    ("limb", 5, 29);
    (* PT_SCX, ucp_Limbu *)
    ("limbu", 5, 29);
    (* PT_SCX, ucp_Limbu *)
    ("lina", 5, 49);
    (* PT_SCX, ucp_Linear_A *)
    ("linb", 5, 31);
    (* PT_SCX, ucp_Linear_B *)
    ("lineara", 5, 49);
    (* PT_SCX, ucp_Linear_A *)
    ("linearb", 5, 31);
    (* PT_SCX, ucp_Linear_B *)
    ("lisu", 4, 111);
    (* PT_SC, ucp_Lisu *)
    ("ll", 3, 5);
    (* PT_PC, ucp_Ll *)
    ("lm", 3, 6);
    (* PT_PC, ucp_Lm *)
    ("lo", 3, 7);
    (* PT_PC, ucp_Lo *)
    ("loe", 13, 33);
    (* PT_BOOL, ucp_Logical_Order_Exception *)
    ("logicalorderexception", 13, 33);
    (* PT_BOOL, ucp_Logical_Order_Exception *)
    ("lower", 13, 34);
    (* PT_BOOL, ucp_Lowercase *)
    ("lowercase", 13, 34);
    (* PT_BOOL, ucp_Lowercase *)
    ("lt", 3, 8);
    (* PT_PC, ucp_Lt *)
    ("lu", 3, 9);
    (* PT_PC, ucp_Lu *)
    ("lyci", 4, 102);
    (* PT_SC, ucp_Lycian *)
    ("lycian", 4, 102);
    (* PT_SC, ucp_Lycian *)
    ("lydi", 4, 104);
    (* PT_SC, ucp_Lydian *)
    ("lydian", 4, 104);
    (* PT_SC, ucp_Lydian *)
    ("m", 2, 2);
    (* PT_GC, ucp_M *)
    ("mahajani", 5, 50);
    (* PT_SCX, ucp_Mahajani *)
    ("mahj", 5, 50);
    (* PT_SCX, ucp_Mahajani *)
    ("maka", 4, 150);
    (* PT_SC, ucp_Makasar *)
    ("makasar", 4, 150);
    (* PT_SC, ucp_Makasar *)
    ("malayalam", 5, 14);
    (* PT_SCX, ucp_Malayalam *)
    ("mand", 5, 42);
    (* PT_SCX, ucp_Mandaic *)
    ("mandaic", 5, 42);
    (* PT_SCX, ucp_Mandaic *)
    ("mani", 5, 51);
    (* PT_SCX, ucp_Manichaean *)
    ("manichaean", 5, 51);
    (* PT_SCX, ucp_Manichaean *)
    ("marc", 4, 143);
    (* PT_SC, ucp_Marchen *)
    ("marchen", 4, 143);
    (* PT_SC, ucp_Marchen *)
    ("masaramgondi", 5, 59);
    (* PT_SCX, ucp_Masaram_Gondi *)
    ("math", 13, 35);
    (* PT_BOOL, ucp_Math *)
    ("mc", 3, 10);
    (* PT_PC, ucp_Mc *)
    ("me", 3, 11);
    (* PT_PC, ucp_Me *)
    ("medefaidrin", 4, 151);
    (* PT_SC, ucp_Medefaidrin *)
    ("medf", 4, 151);
    (* PT_SC, ucp_Medefaidrin *)
    ("meeteimayek", 4, 113);
    (* PT_SC, ucp_Meetei_Mayek *)
    ("mend", 4, 129);
    (* PT_SC, ucp_Mende_Kikakui *)
    ("mendekikakui", 4, 129);
    (* PT_SC, ucp_Mende_Kikakui *)
    ("merc", 4, 121);
    (* PT_SC, ucp_Meroitic_Cursive *)
    ("mero", 4, 122);
    (* PT_SC, ucp_Meroitic_Hieroglyphs *)
    ("meroiticcursive", 4, 121);
    (* PT_SC, ucp_Meroitic_Cursive *)
    ("meroitichieroglyphs", 4, 122);
    (* PT_SC, ucp_Meroitic_Hieroglyphs *)
    ("miao", 4, 123);
    (* PT_SC, ucp_Miao *)
    ("mlym", 5, 14);
    (* PT_SCX, ucp_Malayalam *)
    ("mn", 3, 12);
    (* PT_PC, ucp_Mn *)
    ("modi", 5, 52);
    (* PT_SCX, ucp_Modi *)
    ("mong", 5, 19);
    (* PT_SCX, ucp_Mongolian *)
    ("mongolian", 5, 19);
    (* PT_SCX, ucp_Mongolian *)
    ("mro", 4, 130);
    (* PT_SC, ucp_Mro *)
    ("mroo", 4, 130);
    (* PT_SC, ucp_Mro *)
    ("mtei", 4, 113);
    (* PT_SC, ucp_Meetei_Mayek *)
    ("mult", 5, 57);
    (* PT_SCX, ucp_Multani *)
    ("multani", 5, 57);
    (* PT_SCX, ucp_Multani *)
    ("myanmar", 5, 16);
    (* PT_SCX, ucp_Myanmar *)
    ("mymr", 5, 16);
    (* PT_SCX, ucp_Myanmar *)
    ("n", 2, 3);
    (* PT_GC, ucp_N *)
    ("nabataean", 4, 132);
    (* PT_SC, ucp_Nabataean *)
    ("nagm", 4, 163);
    (* PT_SC, ucp_Nag_Mundari *)
    ("nagmundari", 4, 163);
    (* PT_SC, ucp_Nag_Mundari *)
    ("nand", 5, 64);
    (* PT_SCX, ucp_Nandinagari *)
    ("nandinagari", 5, 64);
    (* PT_SCX, ucp_Nandinagari *)
    ("narb", 4, 131);
    (* PT_SC, ucp_Old_North_Arabian *)
    ("nbat", 4, 132);
    (* PT_SC, ucp_Nabataean *)
    ("nchar", 13, 36);
    (* PT_BOOL, ucp_Noncharacter_Code_Point *)
    ("nd", 3, 13);
    (* PT_PC, ucp_Nd *)
    ("newa", 4, 144);
    (* PT_SC, ucp_Newa *)
    ("newtailue", 4, 89);
    (* PT_SC, ucp_New_Tai_Lue *)
    ("nko", 5, 38);
    (* PT_SCX, ucp_Nko *)
    ("nkoo", 5, 38);
    (* PT_SCX, ucp_Nko *)
    ("nl", 3, 14);
    (* PT_PC, ucp_Nl *)
    ("no", 3, 15);
    (* PT_PC, ucp_No *)
    ("noncharactercodepoint", 13, 36);
    (* PT_BOOL, ucp_Noncharacter_Code_Point *)
    ("nshu", 4, 147);
    (* PT_SC, ucp_Nushu *)
    ("nushu", 4, 147);
    (* PT_SC, ucp_Nushu *)
    ("nyiakengpuachuehmong", 4, 154);
    (* PT_SC, ucp_Nyiakeng_Puachue_Hmong *)
    ("ogam", 4, 78);
    (* PT_SC, ucp_Ogham *)
    ("ogham", 4, 78);
    (* PT_SC, ucp_Ogham *)
    ("olchiki", 4, 98);
    (* PT_SC, ucp_Ol_Chiki *)
    ("olck", 4, 98);
    (* PT_SC, ucp_Ol_Chiki *)
    ("oldhungarian", 4, 140);
    (* PT_SC, ucp_Old_Hungarian *)
    ("olditalic", 4, 81);
    (* PT_SC, ucp_Old_Italic *)
    ("oldnortharabian", 4, 131);
    (* PT_SC, ucp_Old_North_Arabian *)
    ("oldpermic", 5, 53);
    (* PT_SCX, ucp_Old_Permic *)
    ("oldpersian", 4, 91);
    (* PT_SC, ucp_Old_Persian *)
    ("oldsogdian", 4, 152);
    (* PT_SC, ucp_Old_Sogdian *)
    ("oldsoutharabian", 4, 115);
    (* PT_SC, ucp_Old_South_Arabian *)
    ("oldturkic", 4, 118);
    (* PT_SC, ucp_Old_Turkic *)
    ("olduyghur", 5, 67);
    (* PT_SCX, ucp_Old_Uyghur *)
    ("oriya", 5, 10);
    (* PT_SCX, ucp_Oriya *)
    ("orkh", 4, 118);
    (* PT_SC, ucp_Old_Turkic *)
    ("orya", 5, 10);
    (* PT_SCX, ucp_Oriya *)
    ("osage", 4, 145);
    (* PT_SC, ucp_Osage *)
    ("osge", 4, 145);
    (* PT_SC, ucp_Osage *)
    ("osma", 4, 87);
    (* PT_SC, ucp_Osmanya *)
    ("osmanya", 4, 87);
    (* PT_SC, ucp_Osmanya *)
    ("ougr", 5, 67);
    (* PT_SCX, ucp_Old_Uyghur *)
    ("p", 2, 4);
    (* PT_GC, ucp_P *)
    ("pahawhhmong", 4, 128);
    (* PT_SC, ucp_Pahawh_Hmong *)
    ("palm", 4, 133);
    (* PT_SC, ucp_Palmyrene *)
    ("palmyrene", 4, 133);
    (* PT_SC, ucp_Palmyrene *)
    ("patsyn", 13, 37);
    (* PT_BOOL, ucp_Pattern_Syntax *)
    ("patternsyntax", 13, 37);
    (* PT_BOOL, ucp_Pattern_Syntax *)
    ("patternwhitespace", 13, 38);
    (* PT_BOOL, ucp_Pattern_White_Space *)
    ("patws", 13, 38);
    (* PT_BOOL, ucp_Pattern_White_Space *)
    ("pauc", 4, 134);
    (* PT_SC, ucp_Pau_Cin_Hau *)
    ("paucinhau", 4, 134);
    (* PT_SC, ucp_Pau_Cin_Hau *)
    ("pc", 3, 16);
    (* PT_PC, ucp_Pc *)
    ("pcm", 13, 39);
    (* PT_BOOL, ucp_Prepended_Concatenation_Mark *)
    ("pd", 3, 17);
    (* PT_PC, ucp_Pd *)
    ("pe", 3, 18);
    (* PT_PC, ucp_Pe *)
    ("perm", 5, 53);
    (* PT_SCX, ucp_Old_Permic *)
    ("pf", 3, 19);
    (* PT_PC, ucp_Pf *)
    ("phag", 5, 37);
    (* PT_SCX, ucp_Phags_Pa *)
    ("phagspa", 5, 37);
    (* PT_SCX, ucp_Phags_Pa *)
    ("phli", 4, 117);
    (* PT_SC, ucp_Inscriptional_Pahlavi *)
    ("phlp", 5, 54);
    (* PT_SCX, ucp_Psalter_Pahlavi *)
    ("phnx", 4, 95);
    (* PT_SC, ucp_Phoenician *)
    ("phoenician", 4, 95);
    (* PT_SC, ucp_Phoenician *)
    ("pi", 3, 20);
    (* PT_PC, ucp_Pi *)
    ("plrd", 4, 123);
    (* PT_SC, ucp_Miao *)
    ("po", 3, 21);
    (* PT_PC, ucp_Po *)
    ("prependedconcatenationmark", 13, 39);
    (* PT_BOOL, ucp_Prepended_Concatenation_Mark *)
    ("prti", 4, 116);
    (* PT_SC, ucp_Inscriptional_Parthian *)
    ("ps", 3, 22);
    (* PT_PC, ucp_Ps *)
    ("psalterpahlavi", 5, 54);
    (* PT_SCX, ucp_Psalter_Pahlavi *)
    ("qaac", 5, 34);
    (* PT_SCX, ucp_Coptic *)
    ("qaai", 4, 84);
    (* PT_SC, ucp_Inherited *)
    ("qmark", 13, 40);
    (* PT_BOOL, ucp_Quotation_Mark *)
    ("quotationmark", 13, 40);
    (* PT_BOOL, ucp_Quotation_Mark *)
    ("radical", 13, 41);
    (* PT_BOOL, ucp_Radical *)
    ("regionalindicator", 13, 42);
    (* PT_BOOL, ucp_Regional_Indicator *)
    ("rejang", 4, 101);
    (* PT_SC, ucp_Rejang *)
    ("ri", 13, 42);
    (* PT_BOOL, ucp_Regional_Indicator *)
    ("rjng", 4, 101);
    (* PT_SC, ucp_Rejang *)
    ("rohg", 5, 62);
    (* PT_SCX, ucp_Hanifi_Rohingya *)
    ("runic", 4, 79);
    (* PT_SC, ucp_Runic *)
    ("runr", 4, 79);
    (* PT_SC, ucp_Runic *)
    ("s", 2, 5);
    (* PT_GC, ucp_S *)
    ("samaritan", 4, 110);
    (* PT_SC, ucp_Samaritan *)
    ("samr", 4, 110);
    (* PT_SC, ucp_Samaritan *)
    ("sarb", 4, 115);
    (* PT_SC, ucp_Old_South_Arabian *)
    ("saur", 4, 100);
    (* PT_SC, ucp_Saurashtra *)
    ("saurashtra", 4, 100);
    (* PT_SC, ucp_Saurashtra *)
    ("sc", 3, 23);
    (* PT_PC, ucp_Sc *)
    ("sd", 13, 44);
    (* PT_BOOL, ucp_Soft_Dotted *)
    ("sentenceterminal", 13, 43);
    (* PT_BOOL, ucp_Sentence_Terminal *)
    ("sgnw", 4, 141);
    (* PT_SC, ucp_SignWriting *)
    ("sharada", 5, 44);
    (* PT_SCX, ucp_Sharada *)
    ("shavian", 4, 86);
    (* PT_SC, ucp_Shavian *)
    ("shaw", 4, 86);
    (* PT_SC, ucp_Shavian *)
    ("shrd", 5, 44);
    (* PT_SCX, ucp_Sharada *)
    ("sidd", 4, 135);
    (* PT_SC, ucp_Siddham *)
    ("siddham", 4, 135);
    (* PT_SC, ucp_Siddham *)
    ("signwriting", 4, 141);
    (* PT_SC, ucp_SignWriting *)
    ("sind", 5, 55);
    (* PT_SCX, ucp_Khudawadi *)
    ("sinh", 5, 15);
    (* PT_SCX, ucp_Sinhala *)
    ("sinhala", 5, 15);
    (* PT_SCX, ucp_Sinhala *)
    ("sk", 3, 24);
    (* PT_PC, ucp_Sk *)
    ("sm", 3, 25);
    (* PT_PC, ucp_Sm *)
    ("so", 3, 26);
    (* PT_PC, ucp_So *)
    ("softdotted", 13, 44);
    (* PT_BOOL, ucp_Soft_Dotted *)
    ("sogd", 5, 63);
    (* PT_SCX, ucp_Sogdian *)
    ("sogdian", 5, 63);
    (* PT_SCX, ucp_Sogdian *)
    ("sogo", 4, 152);
    (* PT_SC, ucp_Old_Sogdian *)
    ("sora", 4, 124);
    (* PT_SC, ucp_Sora_Sompeng *)
    ("sorasompeng", 4, 124);
    (* PT_SC, ucp_Sora_Sompeng *)
    ("soyo", 4, 148);
    (* PT_SC, ucp_Soyombo *)
    ("soyombo", 4, 148);
    (* PT_SC, ucp_Soyombo *)
    ("space", 13, 49);
    (* PT_BOOL, ucp_White_Space *)
    ("sterm", 13, 43);
    (* PT_BOOL, ucp_Sentence_Terminal *)
    ("sund", 4, 96);
    (* PT_SC, ucp_Sundanese *)
    ("sundanese", 4, 96);
    (* PT_SC, ucp_Sundanese *)
    ("sylo", 5, 36);
    (* PT_SCX, ucp_Syloti_Nagri *)
    ("sylotinagri", 5, 36);
    (* PT_SCX, ucp_Syloti_Nagri *)
    ("syrc", 5, 4);
    (* PT_SCX, ucp_Syriac *)
    ("syriac", 5, 4);
    (* PT_SCX, ucp_Syriac *)
    ("tagalog", 5, 25);
    (* PT_SCX, ucp_Tagalog *)
    ("tagb", 5, 28);
    (* PT_SCX, ucp_Tagbanwa *)
    ("tagbanwa", 5, 28);
    (* PT_SCX, ucp_Tagbanwa *)
    ("taile", 5, 30);
    (* PT_SCX, ucp_Tai_Le *)
    ("taitham", 4, 106);
    (* PT_SC, ucp_Tai_Tham *)
    ("taiviet", 4, 107);
    (* PT_SC, ucp_Tai_Viet *)
    ("takr", 5, 45);
    (* PT_SCX, ucp_Takri *)
    ("takri", 5, 45);
    (* PT_SCX, ucp_Takri *)
    ("tale", 5, 30);
    (* PT_SCX, ucp_Tai_Le *)
    ("talu", 4, 89);
    (* PT_SC, ucp_New_Tai_Lue *)
    ("tamil", 5, 11);
    (* PT_SCX, ucp_Tamil *)
    ("taml", 5, 11);
    (* PT_SCX, ucp_Tamil *)
    ("tang", 4, 146);
    (* PT_SC, ucp_Tangut *)
    ("tangsa", 4, 159);
    (* PT_SC, ucp_Tangsa *)
    ("tangut", 4, 146);
    (* PT_SC, ucp_Tangut *)
    ("tavt", 4, 107);
    (* PT_SC, ucp_Tai_Viet *)
    ("telu", 5, 12);
    (* PT_SCX, ucp_Telugu *)
    ("telugu", 5, 12);
    (* PT_SCX, ucp_Telugu *)
    ("term", 13, 45);
    (* PT_BOOL, ucp_Terminal_Punctuation *)
    ("terminalpunctuation", 13, 45);
    (* PT_BOOL, ucp_Terminal_Punctuation *)
    ("tfng", 4, 90);
    (* PT_SC, ucp_Tifinagh *)
    ("tglg", 5, 25);
    (* PT_SCX, ucp_Tagalog *)
    ("thaa", 5, 5);
    (* PT_SCX, ucp_Thaana *)
    ("thaana", 5, 5);
    (* PT_SCX, ucp_Thaana *)
    ("thai", 4, 72);
    (* PT_SC, ucp_Thai *)
    ("tibetan", 4, 74);
    (* PT_SC, ucp_Tibetan *)
    ("tibt", 4, 74);
    (* PT_SC, ucp_Tibetan *)
    ("tifinagh", 4, 90);
    (* PT_SC, ucp_Tifinagh *)
    ("tirh", 5, 56);
    (* PT_SCX, ucp_Tirhuta *)
    ("tirhuta", 5, 56);
    (* PT_SCX, ucp_Tirhuta *)
    ("tnsa", 4, 159);
    (* PT_SC, ucp_Tangsa *)
    ("toto", 4, 160);
    (* PT_SC, ucp_Toto *)
    ("ugar", 4, 85);
    (* PT_SC, ucp_Ugaritic *)
    ("ugaritic", 4, 85);
    (* PT_SC, ucp_Ugaritic *)
    ("uideo", 13, 46);
    (* PT_BOOL, ucp_Unified_Ideograph *)
    ("unifiedideograph", 13, 46);
    (* PT_BOOL, ucp_Unified_Ideograph *)
    ("unknown", 4, 68);
    (* PT_SC, ucp_Unknown *)
    ("upper", 13, 47);
    (* PT_BOOL, ucp_Uppercase *)
    ("uppercase", 13, 47);
    (* PT_BOOL, ucp_Uppercase *)
    ("vai", 4, 99);
    (* PT_SC, ucp_Vai *)
    ("vaii", 4, 99);
    (* PT_SC, ucp_Vai *)
    ("variationselector", 13, 48);
    (* PT_BOOL, ucp_Variation_Selector *)
    ("vith", 4, 161);
    (* PT_SC, ucp_Vithkuqi *)
    ("vithkuqi", 4, 161);
    (* PT_SC, ucp_Vithkuqi *)
    ("vs", 13, 48);
    (* PT_BOOL, ucp_Variation_Selector *)
    ("wancho", 4, 155);
    (* PT_SC, ucp_Wancho *)
    ("wara", 4, 136);
    (* PT_SC, ucp_Warang_Citi *)
    ("warangciti", 4, 136);
    (* PT_SC, ucp_Warang_Citi *)
    ("wcho", 4, 155);
    (* PT_SC, ucp_Wancho *)
    ("whitespace", 13, 49);
    (* PT_BOOL, ucp_White_Space *)
    ("wspace", 13, 49);
    (* PT_BOOL, ucp_White_Space *)
    ("xan", 6, 0);
    (* PT_ALNUM, 0 *)
    ("xidc", 13, 50);
    (* PT_BOOL, ucp_XID_Continue *)
    ("xidcontinue", 13, 50);
    (* PT_BOOL, ucp_XID_Continue *)
    ("xids", 13, 51);
    (* PT_BOOL, ucp_XID_Start *)
    ("xidstart", 13, 51);
    (* PT_BOOL, ucp_XID_Start *)
    ("xpeo", 4, 91);
    (* PT_SC, ucp_Old_Persian *)
    ("xps", 8, 0);
    (* PT_PXSPACE, 0 *)
    ("xsp", 7, 0);
    (* PT_SPACE, 0 *)
    ("xsux", 4, 94);
    (* PT_SC, ucp_Cuneiform *)
    ("xuc", 11, 0);
    (* PT_UCNC, 0 *)
    ("xwd", 9, 0);
    (* PT_WORD, 0 *)
    ("yezi", 5, 65);
    (* PT_SCX, ucp_Yezidi *)
    ("yezidi", 5, 65);
    (* PT_SCX, ucp_Yezidi *)
    ("yi", 5, 24);
    (* PT_SCX, ucp_Yi *)
    ("yiii", 5, 24);
    (* PT_SCX, ucp_Yi *)
    ("z", 2, 6);
    (* PT_GC, ucp_Z *)
    ("zanabazarsquare", 4, 149);
    (* PT_SC, ucp_Zanabazar_Square *)
    ("zanb", 4, 149);
    (* PT_SC, ucp_Zanabazar_Square *)
    ("zinh", 4, 84);
    (* PT_SC, ucp_Inherited *)
    ("zl", 3, 27);
    (* PT_PC, ucp_Zl *)
    ("zp", 3, 28);
    (* PT_PC, ucp_Zp *)
    ("zs", 3, 29);
    (* PT_PC, ucp_Zs *)
    ("zyyy", 4, 69);
    (* PT_SC, ucp_Common *)
    ("zzzz", 4, 68);
    (* PT_SC, ucp_Unknown *)
  |]

(* pcre2_ucptables.c:1529 *)
let utt_size = 489
